In [2]:
import numpy as np
import random
import math

In [3]:
arr = [10 + random.randint(1, 1000) for i in xrange(1000)]

In [4]:
hist, bin_edges = np.histogram(arr, density=True)

In [5]:
cdf = np.cumsum(hist*np.diff(bin_edges))

In [6]:
cdff = [cd * math.log(cd, 2) for cd in cdf]

In [7]:
-sum(cdff * np.diff(bin_edges))

355.31693631679752

In [8]:
arr2 = np.random.randint(1, 100, 1000)

In [9]:
arr2

array([96,  6, 31, 96, 89, 90, 64, 30, 12, 61, 69, 94, 95, 35, 90, 16,  9,
       91,  6, 29, 80, 45, 54, 16,  1, 81, 85,  4, 74, 32, 74, 62, 46, 22,
       70, 80, 17, 40, 80, 20, 16, 99, 34, 99, 45, 51, 50, 19, 99, 85, 18,
       23, 63, 28, 94, 75, 69,  7, 26, 91, 88, 22, 26, 33, 96, 81, 48, 17,
       98,  5, 52, 26, 57, 87, 84, 27,  7,  8, 54,  4, 32, 57, 97, 76, 68,
       41,  8, 70, 74, 18, 40,  5, 60, 50, 16, 44, 99, 32, 44, 16, 18, 69,
       49, 45, 21,  8, 65, 64, 63, 75, 43, 32, 79, 54, 84, 74, 47, 34, 14,
       11, 40, 16, 89, 10, 32, 24,  9, 41, 96, 39, 92, 53, 58, 67, 60, 79,
       27, 90, 27, 85, 88, 33, 11, 34, 54, 72, 96, 14, 93, 69, 62, 32,  8,
        3, 89, 24,  5, 72, 86, 21, 71, 53, 73, 71,  3, 71, 46, 28, 95, 25,
       22, 67, 76, 11, 42, 89, 59, 74, 58, 15,  4, 86,  9, 19, 81, 54, 10,
       81, 55, 38, 80, 80, 87, 85, 30,  3,  7, 40, 82,  3, 56, 91, 51, 18,
       65, 98,  5, 91, 40, 13, 33, 63, 71, 42, 80, 41, 30, 16, 54, 47, 59,
       80, 25, 24, 56,  3

In [10]:
arr_x = arr2
arr_y = [i+10 for i in arr_x]

In [11]:
arr_y

[106,
 16,
 41,
 106,
 99,
 100,
 74,
 40,
 22,
 71,
 79,
 104,
 105,
 45,
 100,
 26,
 19,
 101,
 16,
 39,
 90,
 55,
 64,
 26,
 11,
 91,
 95,
 14,
 84,
 42,
 84,
 72,
 56,
 32,
 80,
 90,
 27,
 50,
 90,
 30,
 26,
 109,
 44,
 109,
 55,
 61,
 60,
 29,
 109,
 95,
 28,
 33,
 73,
 38,
 104,
 85,
 79,
 17,
 36,
 101,
 98,
 32,
 36,
 43,
 106,
 91,
 58,
 27,
 108,
 15,
 62,
 36,
 67,
 97,
 94,
 37,
 17,
 18,
 64,
 14,
 42,
 67,
 107,
 86,
 78,
 51,
 18,
 80,
 84,
 28,
 50,
 15,
 70,
 60,
 26,
 54,
 109,
 42,
 54,
 26,
 28,
 79,
 59,
 55,
 31,
 18,
 75,
 74,
 73,
 85,
 53,
 42,
 89,
 64,
 94,
 84,
 57,
 44,
 24,
 21,
 50,
 26,
 99,
 20,
 42,
 34,
 19,
 51,
 106,
 49,
 102,
 63,
 68,
 77,
 70,
 89,
 37,
 100,
 37,
 95,
 98,
 43,
 21,
 44,
 64,
 82,
 106,
 24,
 103,
 79,
 72,
 42,
 18,
 13,
 99,
 34,
 15,
 82,
 96,
 31,
 81,
 63,
 83,
 81,
 13,
 81,
 56,
 38,
 105,
 35,
 32,
 77,
 86,
 21,
 52,
 99,
 69,
 84,
 68,
 25,
 14,
 96,
 19,
 29,
 91,
 64,
 20,
 91,
 65,
 48,
 90,
 90,
 97,
 95,
 40,
 13

In [12]:
hist, bin_edges = np.histogram(arr_x, density=True)

In [13]:
hist

array([ 0.01102041,  0.01102041,  0.01020408,  0.01      ,  0.00897959,
        0.00989796,  0.00806122,  0.01132653,  0.01112245,  0.01040816])

In [14]:
bin_edges

array([  1. ,  10.8,  20.6,  30.4,  40.2,  50. ,  59.8,  69.6,  79.4,
        89.2,  99. ])

In [15]:
hist, bin_edges = np.histogram(arr_y, density=True)

In [16]:
hist

array([ 0.01102041,  0.01102041,  0.01020408,  0.01      ,  0.00897959,
        0.00989796,  0.00806122,  0.01132653,  0.01112245,  0.01040816])